#!/usr/bin/with-contenv bash
cat <<'banner'

 ____          _              _____         ___ ___ _        _____         _           _
|    \ ___ ___| |_ ___ ___   |_   _|___ ___|  _|  _|_|___   |     |___ ___| |_ ___ ___| |
|  |  | . |  _| '_| -_|  _|    | | |  _| .'|  _|  _| |  _|  |   --| . |   |  _|  _| . | |
|____/|___|___|_,_|___|_|      |_| |_| |__,|_| |_| |_|___|  |_____|___|_|_|_| |_| |___|_|

banner
echo "Starting Docker Traffic Control $DOCKER_TC_VERSION"
echo "https://github.com/lukaszlach/docker-tc"
echo
exec bash /docker-tc/bin/docker-tc.sh